### ISSUE TITLE
Unable to pass the ProductProvisioning stage of the pipeline

### ISSUE THREAD

**Issue by papiveron** [awslabs/aws-service-catalog-validation-pipeline#3]
Hi,

I've been searching everywere for many hours and don't understand this error, which is making the validation pipeline ecah time at **ProductProvisioning** stage in the provision_product lambda invokation action...

```
incomplete format: ValueError
Traceback (most recent call last):
File "/var/task/provision_product.py", line 41, in lambda_handler
stacks = pipeline_run.provision_product()
File "/var/task/cfnpipeline.py", line 976, in provision_product
results = pool.map(func, regions)
File "/usr/lib64/python2.7/multiprocessing/pool.py", line 251, in map
return self.map_async(func, iterable, chunksize).get()
File "/usr/lib64/python2.7/multiprocessing/pool.py", line 567, in get
raise self._value
ValueError: incomplete format
```
I look into the code, I tried to print all parameter values passed to the partial function when creating the **partial** object returning **func** to be passed in the 

> pool.map(func, regions) 

call .
All paremeters are defined and none is empty, the regions value is a list : 

>  ["eu-west-1", "us-east-1"]

This are parameters values print for debug :
```
args and kwargs : ========>>>>>>>>>
provision_artifact ==>> : <bound method CFNPipeline._provision_product of <cfnpipeline.CFNPipeline object at 0x7f5d0280fd10>>
artifact ==>>: TemplateArtifact
testname ==>> : defaults
template_url  ==>>: https://s3-eu-west-1.amazonaws.com/main-sc-pipeline-scratchbucket-y07mvrp5gbt4/scratch/TemplateArtifact/180717-161453-986235-4d08aafa-4363-4551-8151-14c497b29241/aws-vpc.template
parameter_input ==>>: [{u'ParameterValue': u'$[alfred_genaz_2]', u'ParameterKey': u'AvailabilityZones'}, {u'ParameterValue': u'false', u'ParameterKey': u'CreateAdditionalPrivateSubnets'}, {u'ParameterValue': u'true', u'ParameterKey': u'CreatePrivateSubnets'}, {u'ParameterValue': u'$[alfred_getkeypair]', u'ParameterKey': u'KeyPairName'}, {u'ParameterValue': u't2.small', u'ParameterKey': u'NATInstanceT
StackCreationRoleArn ==>> : arn:aws:iam::522409712140:role/cfn-central-microservices-sc-ProvisionProductsRole-GUOYX4GOUGG6
KeyBucket ==>>: main-sc-pipeline-keybucket-b791fxaaxjdt
func, regions ==>> : <functools.partial object at 0x7f5d00139578> ['us-east-1', 'eu-west-1']
````
I don't understand why python is still complaining about format error....

Did somone tested and  get this error please?

Thanks,
Regards

**Comment by papiveron** [comment]
I found the issue, it was in the provision_product function.

The **StackCreationRoleArn** role was not servicecatalog trusted, neither permited **iam:PassRole**  from the the provision_product lambda function's role
